# $$\text{Practical 5}$$

## Name : Krishna Mundada
## Roll no : 45
## Section : E3
## Subject : Python Programming Lab (CAP 201)
## Topic : Numpy


### 1. Write a python code for addition, subtraction and multiplication of two 4x4 matrices.

In [1]:
import numpy as np

arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,3,6,2],[5,2,7,3]])
arr2 = np.array([[7,9,3,4],[5,3,7,9],[7,3,2,2],[8,9,7,1]])

print("Additon:\n",arr1+arr2)
print("\nSubtraction:\n",arr1-arr2)
print("\nMultiplication:\n",np.dot(arr1,arr2))

Additon:
 [[ 8 11  6  8]
 [10  9 14 17]
 [16  6  8  4]
 [13 11 14  4]]

Subtraction:
 [[-6 -7  0  0]
 [ 0  3  0 -1]
 [ 2  0  4  0]
 [-3 -7  0  2]]

Multiplication:
 [[ 70  60  51  32]
 [178 156 127  96]
 [136 126  74  77]
 [118  99  64  55]]


### 2. Create a 5 by 2 integer array from a range between 100 to200 such that the difference between each element is 10.Print the same.

In [2]:
arr = np.arange(100,200,10)
arr=arr.reshape(5,2)
print("5x2 Array:\n\n",arr)

5x2 Array:

 [[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


### 3. Consider two matrices
### M1=([[2,3,4], [6,5,2], [6,7,3]])
### M2=([[1,4,2], [4,3,6],[5,9,8]])
### Calculate manually as well as develop the python programfor the following:
### (1) matrix multiplication (dot product) (2) inner product (3)cross product (4) outer product

In [3]:
M1=([[2,3,4],[6,5,2],[6,7,3]])
M2=([[1,4,2],[4,3,6],[5,9,8]])

r1 = np.dot(M1,M2)
r2 = np.inner(M1,M2)
r3 = np.cross(M1,M2)
r4 = np.outer(M1,M2)
print("Multiplication(Dot Product) : \n",r1)
print("\nInner Product : \n",r2)
print("\nCross Product : \n",r3)
print("\nOuter Product : \n",r4)

Multiplication(Dot Product) : 
 [[34 53 54]
 [36 57 58]
 [49 72 78]]

Inner Product : 
 [[ 22  41  69]
 [ 30  51  91]
 [ 40  63 117]]

Cross Product : 
 [[-10   0   5]
 [ 24 -28  -2]
 [ 29 -33  19]]

Outer Product : 
 [[ 2  8  4  8  6 12 10 18 16]
 [ 3 12  6 12  9 18 15 27 24]
 [ 4 16  8 16 12 24 20 36 32]
 [ 6 24 12 24 18 36 30 54 48]
 [ 5 20 10 20 15 30 25 45 40]
 [ 2  8  4  8  6 12 10 18 16]
 [ 6 24 12 24 18 36 30 54 48]
 [ 7 28 14 28 21 42 35 63 56]
 [ 3 12  6 12  9 18 15 27 24]]


### 4. Randomly generate the marks of the 80 students in the range of 40 to 95. Write a NumPy program to compute the 70 percentile for all elements in a given array. (Hint: use np.random.randint(start,stop,no_of_items) for list generation) (Hint: Use np.percentile)

In [4]:
print("Random marks:")
arr = np.random.randint(40,95,80)
print(arr)
per = np.percentile(arr,70)
print("\n70th percentile :",per)

Random marks:
[52 57 81 84 56 72 42 80 51 70 44 89 66 79 63 51 73 78 57 44 66 50 82 52
 67 92 62 82 69 89 41 67 75 63 84 71 86 59 83 87 56 60 94 50 57 70 82 88
 57 54 78 57 48 68 67 57 58 62 92 44 51 43 75 41 41 59 73 84 45 60 90 40
 77 40 58 79 78 92 53 45]

70th percentile : 77.3


### 5. Write a NumPy program to compute the eigen values and right eigenvectors of a given square array.
### Arr =([[1,4,8], [8,9,2],[9,7,8]])
### HINT: Use linear algebra package under numpy. Add these statements i.e. for eigenvalues, import numpy as np from numpy import linalg np.linalg.eig(a)

In [5]:
arr =([[1,4,8],[8,9,2],[9,7,8]])

u,v = np.linalg.eig(arr)
print( "Eigenvalues of the matrix:",u)
print( "\nEigenvectors of the matrix:\n",v)

Eigenvalues of the matrix: [18.61713304 -4.50451282  3.88737977]

Eigenvectors of the matrix:
 [[-0.44798294 -0.82768979  0.36471887]
 [-0.52339057  0.43844259 -0.77347804]
 [-0.7248266   0.35028233  0.51837426]]
